### ISSUE TITLE
Failing serverspec tests

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/vagrant-flapjack#21]
On Trusty (default): 

```text
$ rake serverspec
...
Failures:

  1) File "/var/log/flapjack/flapjack.log" should be owned by "flapjack"
     On host `127.0.0.1'
     Failure/Error: it { should be_owned_by 'flapjack' }
       expected `File "/var/log/flapjack/flapjack.log".owned_by?("flapjack")` to return true, got false
       sudo -p 'Password: ' /bin/sh -c stat\ -c\ \%U\ /var/log/flapjack/flapjack.log\ \|\ grep\ --\ \\\^flapjack\\\$

     # ./spec/serverspec/flapjack_spec.rb:65:in `block (2 levels) in <top (required)>'

  2) File "/var/log/flapjack/flapjack.log" should be grouped into "flapjack"
     On host `127.0.0.1'
     Failure/Error: it { should be_grouped_into 'flapjack' }
       expected `File "/var/log/flapjack/flapjack.log".grouped_into?("flapjack")` to return true, got false
       sudo -p 'Password: ' /bin/sh -c stat\ -c\ \%G\ /var/log/flapjack/flapjack.log\ \|\ grep\ --\ \\\^flapjack\\\$

     # ./spec/serverspec/flapjack_spec.rb:66:in `block (2 levels) in <top (required)>'

  3) File "/var/log/flapjack/notification.log" should be owned by "flapjack"
     On host `127.0.0.1'
     Failure/Error: it { should be_owned_by 'flapjack' }
       expected `File "/var/log/flapjack/notification.log".owned_by?("flapjack")` to return true, got false
       sudo -p 'Password: ' /bin/sh -c stat\ -c\ \%U\ /var/log/flapjack/notification.log\ \|\ grep\ --\ \\\^flapjack\\\$

     # ./spec/serverspec/flapjack_spec.rb:72:in `block (2 levels) in <top (required)>'

  4) File "/var/log/flapjack/notification.log" should be grouped into "flapjack"
     On host `127.0.0.1'
     Failure/Error: it { should be_grouped_into 'flapjack' }
       expected `File "/var/log/flapjack/notification.log".grouped_into?("flapjack")` to return true, got false
       sudo -p 'Password: ' /bin/sh -c stat\ -c\ \%G\ /var/log/flapjack/notification.log\ \|\ grep\ --\ \\\^flapjack\\\$

     # ./spec/serverspec/flapjack_spec.rb:73:in `block (2 levels) in <top (required)>'

  5) File "/var/log/flapjack/jsonapi_access.log" should be owned by "flapjack"
     On host `127.0.0.1'
     Failure/Error: it { should be_owned_by 'flapjack' }
       expected `File "/var/log/flapjack/jsonapi_access.log".owned_by?("flapjack")` to return true, got false
       sudo -p 'Password: ' /bin/sh -c stat\ -c\ \%U\ /var/log/flapjack/jsonapi_access.log\ \|\ grep\ --\ \\\^flapjack\\\$

     # ./spec/serverspec/flapjack_spec.rb:79:in `block (2 levels) in <top (required)>'

  6) File "/var/log/flapjack/jsonapi_access.log" should be grouped into "flapjack"
     On host `127.0.0.1'
     Failure/Error: it { should be_grouped_into 'flapjack' }
       expected `File "/var/log/flapjack/jsonapi_access.log".grouped_into?("flapjack")` to return true, got false
       sudo -p 'Password: ' /bin/sh -c stat\ -c\ \%G\ /var/log/flapjack/jsonapi_access.log\ \|\ grep\ --\ \\\^flapjack\\\$

     # ./spec/serverspec/flapjack_spec.rb:80:in `block (2 levels) in <top (required)>'

  7) File "/var/log/flapjack/redis-flapjack.log" should be mode 644
     On host `127.0.0.1'
     Failure/Error: it { should be_mode 644 }
       expected `File "/var/log/flapjack/redis-flapjack.log".mode?(644)` to return true, got false
       sudo -p 'Password: ' /bin/sh -c stat\ -c\ \%a\ /var/log/flapjack/redis-flapjack.log\ \|\ grep\ --\ \\\^644\\\$

     # ./spec/serverspec/flapjack_spec.rb:85:in `block (2 levels) in <top (required)>'

  8) File "/var/log/flapjack/web_access.log" should be owned by "flapjack"
     On host `127.0.0.1'
     Failure/Error: it { should be_owned_by 'flapjack' }
       expected `File "/var/log/flapjack/web_access.log".owned_by?("flapjack")` to return true, got false
       sudo -p 'Password: ' /bin/sh -c stat\ -c\ \%U\ /var/log/flapjack/web_access.log\ \|\ grep\ --\ \\\^flapjack\\\$

     # ./spec/serverspec/flapjack_spec.rb:93:in `block (2 levels) in <top (required)>'

  9) File "/var/log/flapjack/web_access.log" should be grouped into "flapjack"
     On host `127.0.0.1'
     Failure/Error: it { should be_grouped_into 'flapjack' }
       expected `File "/var/log/flapjack/web_access.log".grouped_into?("flapjack")` to return true, got false
       sudo -p 'Password: ' /bin/sh -c stat\ -c\ \%G\ /var/log/flapjack/web_access.log\ \|\ grep\ --\ \\\^flapjack\\\$

     # ./spec/serverspec/flapjack_spec.rb:94:in `block (2 levels) in <top (required)>'

Finished in 3.26 seconds (files took 7.43 seconds to load)
57 examples, 9 failures

Failed examples:

rspec ./spec/serverspec/flapjack_spec.rb:65 # File "/var/log/flapjack/flapjack.log" should be owned by "flapjack"
rspec ./spec/serverspec/flapjack_spec.rb:66 # File "/var/log/flapjack/flapjack.log" should be grouped into "flapjack"
rspec ./spec/serverspec/flapjack_spec.rb:72 # File "/var/log/flapjack/notification.log" should be owned by "flapjack"
rspec ./spec/serverspec/flapjack_spec.rb:73 # File "/var/log/flapjack/notification.log" should be grouped into "flapjack"
rspec ./spec/serverspec/flapjack_spec.rb:79 # File "/var/log/flapjack/jsonapi_access.log" should be owned by "flapjack"
rspec ./spec/serverspec/flapjack_spec.rb:80 # File "/var/log/flapjack/jsonapi_access.log" should be grouped into "flapjack"
rspec ./spec/serverspec/flapjack_spec.rb:85 # File "/var/log/flapjack/redis-flapjack.log" should be mode 644
rspec ./spec/serverspec/flapjack_spec.rb:93 # File "/var/log/flapjack/web_access.log" should be owned by "flapjack"
rspec ./spec/serverspec/flapjack_spec.rb:94 # File "/var/log/flapjack/web_access.log" should be grouped into "flapjack"
```

**Comment by Hobbsee** [comment]
Possibly related: https://github.com/flapjack/omnibus-flapjack/issues/62

Interestingly, when this trusty package was built, only 'File "/var/log/flapjack/redis-flapjack.log" should be mode 644 failed', but the rest of the tests passed.  The tests were run against the package for experimental, not the repacked one for main.

**Comment by Hobbsee** [comment]
I've fixed the block of tests omnibus-flapjack uses (which should be identical to these).  I'll investigate further after our next builds.

**Comment by Hobbsee** [comment]
See https://github.com/flapjack/omnibus-flapjack/issues/74
